name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"  # Trigger when changes are pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Runs on an x86-based runner

    steps:
    # Step 1: Check out your repository
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Step 3: Build and push the Docker image
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/teacherflow-api:latest

    # Optional Step 4: Verify the built image
    - name: Show built image details
      run: |
        echo "Listing images in DockerHub repository..."
        curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/teacherflow-api/tags/ | jq '.'